const PERMISSION_CODE = {
  ADD_INVENTORY: "ADD_INVENTORY",
  EDIT_INVENTORY: "EDIT_INVENTORY",
  DELETE_INVENTORY: "DELETE_INVENTORY",
  CHECKOUT_INVENTORY: "CHECKOUT_INVENTORY",
  RETURN_INVENTORY: "RETURN_INVENTORY",
  VIEW_ALL_MANAGE_INVENTORY_COLUMN: "VIEW_ALL_MANAGE_INVENTORY_COLUMN",
  VIEW_ALL_USER_CHECKOUT_REPORT: "VIEW_ALL_USER_CHECKOUT_REPORT",
};

export default PERMISSION_CODE;

